-- Seed data: verified UW activities
-- Source of truth: data/uwb_activities.json
-- All entries have verified_by = 'pending' — team must cross-check each row
-- against a live official source before setting verified_by to a team member name.

INSERT INTO activities
  (name, category, campus, description, skills, source_url, active, last_verified, verified_by,
   time_commitment, duration, cost, registration_info, notes)
VALUES

-- ── CLUBS ────────────────────────────────────────────────────────────────────

('ACM at UW Bothell',
 'club',
 'bothell',
 'Student chapter of the Association for Computing Machinery at UW Bothell. Hosts technical workshops, coding competitions, lightning talks, and networking events. Active membership supports resume entries in professional community involvement.',
 ARRAY['algorithms','competitive programming','leadership','networking','professional development'],
 'https://www.uwb.edu/dsa/clubs-organizations',
 TRUE, '2026-05-12', 'pending',
 '2–4 hours/week', 'ongoing, active each quarter', 'free or nominal membership fee',
 'Contact club through the UWB DSA portal or attend interest meetings at the start of each quarter.',
 'Verify current officer contact and meeting schedule against the DSA club directory.'),

('Women in Computing (WiC) at UWB',
 'club',
 'bothell',
 'Campus chapter supporting gender diversity in computing. Organizes mentorship programs, industry panels, hackathons, and professional workshops. Membership provides networking with women in tech and access to WiC-affiliated scholarships.',
 ARRAY['leadership','networking','mentorship','professional development','community building'],
 'https://www.uwb.edu/dsa/clubs-organizations',
 TRUE, '2026-05-12', 'pending',
 '2–3 hours/week', 'ongoing', 'free',
 'Join through UWB DSA portal or attend first-week interest meeting.',
 'Verify chapter is active and confirm whether membership is open to all students or requires application.'),

('UWB Robotics Club',
 'club',
 'bothell',
 'Hands-on robotics club where students build and program autonomous robots for competition and demonstration. Members gain experience with embedded systems, sensor integration, motor control, and team-based hardware-software co-design.',
 ARRAY['robotics','embedded systems','c++','python','hardware','teamwork','problem solving'],
 'https://www.uwb.edu/dsa/clubs-organizations',
 TRUE, '2026-05-12', 'pending',
 '3–6 hours/week', 'ongoing', 'free; some material costs may apply',
 'Contact through DSA portal.',
 'Verify club is currently active and meeting regularly.'),

('UWB Game Development Club',
 'club',
 'bothell',
 'Game development club where students create original games using Unity, Unreal Engine, and web technologies. Members build portfolios of shipped game projects and develop skills in programming, game design, and asset creation.',
 ARRAY['unity','c#','game design','javascript','graphics programming','game development','teamwork'],
 'https://www.uwb.edu/dsa/clubs-organizations',
 TRUE, '2026-05-12', 'pending',
 '3–5 hours/week', 'ongoing', 'free',
 'Join via DSA portal or Discord at the start of each quarter.',
 'Verify club Discord and confirm whether game jam projects are publicly showcased.'),

('UWB Cybersecurity Club',
 'club',
 'bothell',
 'Cybersecurity club focused on capture-the-flag (CTF) competitions, security research, and ethical hacking practice. Members develop hands-on skills in network security, reverse engineering, web exploitation, and cryptography.',
 ARRAY['cybersecurity','ethical hacking','python','networking','linux','ctf','cryptography','reverse engineering'],
 'https://www.uwb.edu/dsa/clubs-organizations',
 TRUE, '2026-05-12', 'pending',
 '2–4 hours/week', 'ongoing', 'free',
 'Contact through DSA portal.',
 'Verify club name (may be listed as CyberDawgs or UWB Security Club) in DSA directory.'),

('UWB Data Science Club',
 'club',
 'bothell',
 'Club for students interested in data science, analytics, and machine learning. Members work on collaborative data projects, participate in Kaggle competitions, and attend talks by industry data scientists.',
 ARRAY['python','pandas','machine learning','data analysis','sql','data visualization','statistics'],
 'https://www.uwb.edu/dsa/clubs-organizations',
 TRUE, '2026-05-12', 'pending',
 '2–4 hours/week', 'ongoing', 'free',
 'Contact through DSA portal.',
 'Verify club is active and whether they run a regular Kaggle competition team.'),

('UWB Entrepreneurship Club',
 'club',
 'bothell',
 'Student entrepreneurship organization supporting startup ideation, business plan development, and connections to the local tech startup ecosystem. Runs pitch competitions and links members to UWB entrepreneurship resources.',
 ARRAY['entrepreneurship','product management','leadership','business development','public speaking','pitching'],
 'https://www.uwb.edu/dsa/clubs-organizations',
 TRUE, '2026-05-12', 'pending',
 '2–3 hours/week', 'ongoing', 'free',
 'Contact through DSA portal.',
 'Confirm if affiliated with any external startup accelerators or the Foster School of Business.'),

('UWB Math Club',
 'club',
 'bothell',
 'Mathematics club offering problem-solving sessions, Putnam Exam preparation, and talks on mathematical topics relevant to computing and engineering. Membership strengthens analytical and proof-writing skills valued in software engineering and research roles.',
 ARRAY['mathematics','algorithms','problem solving','discrete mathematics','statistics','proof writing'],
 'https://www.uwb.edu/dsa/clubs-organizations',
 TRUE, '2026-05-12', 'pending',
 '1–3 hours/week', 'ongoing', 'free',
 'Contact through DSA portal or STEM department.',
 'Verify club is actively meeting and whether Putnam prep sessions are offered.'),

('IEEE Student Branch at UWB',
 'club',
 'bothell',
 'Institute of Electrical and Electronics Engineers student chapter at UWB. Hosts workshops on hardware, networking, and embedded systems. Provides access to the IEEE digital library and entry to national student competitions.',
 ARRAY['hardware','networking','electrical engineering','embedded systems','professional development'],
 'https://www.uwb.edu/dsa/clubs-organizations',
 TRUE, '2026-05-12', 'pending',
 '2–3 hours/week', 'ongoing', 'IEEE student membership fee (~$32/year)',
 'Join through the IEEE website and attend the first UWB chapter meeting.',
 'Verify the UWB branch is currently active (some branches go dormant).'),

('DECA at UWB',
 'club',
 'bothell',
 'Business and entrepreneurship student organization that prepares students for case competitions in marketing, finance, and management. Relevant for CSS students targeting product management, business development, or technical program management roles.',
 ARRAY['business','marketing','leadership','communication','project management','case analysis'],
 'https://www.uwb.edu/dsa/clubs-organizations',
 TRUE, '2026-05-12', 'pending',
 '2–4 hours/week', 'ongoing', 'DECA membership fee applies',
 'Contact through DSA portal.',
 'Verify DECA chapter is active at UWB and confirm competition schedule.'),

('UWB Finance and Investment Club',
 'club',
 'bothell',
 'Club exploring financial markets, investment strategies, and quantitative finance. Students learn financial modeling, data analysis for financial applications, and presentation skills through mock portfolio competitions. Useful for students targeting fintech roles.',
 ARRAY['finance','data analysis','python','excel','quantitative analysis','communication'],
 'https://www.uwb.edu/dsa/clubs-organizations',
 TRUE, '2026-05-12', 'pending',
 '2–3 hours/week', 'ongoing', 'free',
 'Contact through DSA portal.',
 'Verify club is active and separate from DECA.'),

('UWB Pre-Health Society',
 'club',
 'bothell',
 'Pre-health student organization providing academic resources, mentorship, and community service opportunities. Relevant for CSS students targeting health-tech intersections such as medical software, health informatics, and digital health startups.',
 ARRAY['leadership','community service','communication','teamwork','health informatics'],
 'https://www.uwb.edu/dsa/clubs-organizations',
 TRUE, '2026-05-12', 'pending',
 '1–3 hours/week', 'ongoing', 'free',
 'Contact through DSA portal.',
 'Verify club is active and confirm relevance to CSS students.'),

('UWB Psychology Club',
 'club',
 'bothell',
 'Psychology student organization hosting research discussions, speaker events, and volunteer opportunities. Useful for students interested in UX research, human-computer interaction, and user behavior analysis.',
 ARRAY['research','human factors','user research','communication','teamwork'],
 'https://www.uwb.edu/dsa/clubs-organizations',
 TRUE, '2026-05-12', 'pending',
 '1–2 hours/week', 'ongoing', 'free',
 'Contact through DSA portal.',
 'Verify club is active at UWB.'),

('UWB International Student Association',
 'club',
 'bothell',
 'Cultural and community organization supporting international students and cross-cultural exchange at UWB. Develops intercultural communication skills and global perspective valued by multinational tech companies.',
 ARRAY['communication','leadership','community building','cultural competency'],
 'https://www.uwb.edu/dsa/clubs-organizations',
 TRUE, '2026-05-12', 'pending',
 '1–2 hours/week', 'ongoing', 'free',
 'Contact through DSA portal.',
 'Verify club is active and confirm official name in DSA directory.'),

('UWB Environmental Science Club',
 'club',
 'bothell',
 'Student club focused on environmental sustainability and science outreach. Organizes community service projects and educational events. Relevant for students interested in climate tech, GIS, sustainability software, or civic technology roles.',
 ARRAY['sustainability','community engagement','project management','leadership','data analysis'],
 'https://www.uwb.edu/dsa/clubs-organizations',
 TRUE, '2026-05-12', 'pending',
 '1–3 hours/week', 'ongoing', 'free',
 'Contact through DSA portal.',
 'Verify club is active at UWB.'),

-- ── COURSES ──────────────────────────────────────────────────────────────────

('CSS 342 – Data Structures, Algorithms, and Discrete Mathematics I',
 'course',
 'bothell',
 'First course in UWB''s data structures and algorithms sequence. Covers linked lists, stacks, queues, trees, and introductory algorithm analysis using C++. Foundational for technical interview performance at software engineering firms.',
 ARRAY['c++','data structures','algorithms','object-oriented programming','problem solving','discrete mathematics'],
 'https://myplan.uw.edu/course/#/courses/CSS%20342',
 TRUE, '2026-05-12', 'pending',
 '10 weeks, ~15 hours/week', 'one quarter', 'UW tuition',
 'Enroll via UW registration. Check prerequisite (CSS 143 or equivalent).',
 'Offered most quarters. Confirm current offerings on MyPlan.'),

('CSS 343 – Data Structures, Algorithms, and Discrete Mathematics II',
 'course',
 'bothell',
 'Continuation of CSS 342. Covers balanced BSTs, heaps, hash tables, graphs, graph algorithms, and advanced sorting. One of the highest-value courses for passing technical interviews at software engineering firms.',
 ARRAY['c++','data structures','algorithms','graphs','dynamic programming','problem solving'],
 'https://myplan.uw.edu/course/#/courses/CSS%20343',
 TRUE, '2026-05-12', 'pending',
 '10 weeks, ~15 hours/week', 'one quarter', 'UW tuition',
 'Prerequisite: CSS 342.',
 'Offered most quarters. Confirm on MyPlan.'),

('CSS 370 – Technical Writing for Computing and Software Systems',
 'course',
 'bothell',
 'Technical communication course for computing students. Covers specification writing, API documentation, technical reports, and professional communication. Directly applicable to software engineering documentation, technical program management, and developer relations roles.',
 ARRAY['technical writing','documentation','communication','requirements specification','api documentation'],
 'https://myplan.uw.edu/course/#/courses/CSS%20370',
 TRUE, '2026-05-12', 'pending',
 '10 weeks, ~8 hours/week', 'one quarter', 'UW tuition',
 'Prerequisite: English composition. Check SDB for current prerequisite details.',
 'Verify course number and title in current UW catalog.'),

('CSS 422 – Hardware and Computer Organization',
 'course',
 'bothell',
 'Architecture of modern computers including CPU design, memory hierarchy, instruction sets, and I/O systems. Foundational for embedded systems, firmware, systems programming, and hardware-adjacent software engineering.',
 ARRAY['computer architecture','assembly language','hardware','systems programming','c','memory management'],
 'https://myplan.uw.edu/course/#/courses/CSS%20422',
 TRUE, '2026-05-12', 'pending',
 '10 weeks, ~12 hours/week', 'one quarter', 'UW tuition',
 'Check prerequisites on MyPlan.',
 'Confirm offering schedule; may be offered once per year.'),

('CSS 430 – Operating Systems',
 'course',
 'bothell',
 'Covers processes, threads, scheduling, memory management, file systems, and synchronization primitives. Highly relevant for backend infrastructure, cloud systems, embedded software, and systems engineering roles.',
 ARRAY['operating systems','c','c++','linux','multithreading','memory management','systems programming','concurrency'],
 'https://myplan.uw.edu/course/#/courses/CSS%20430',
 TRUE, '2026-05-12', 'pending',
 '10 weeks, ~15 hours/week', 'one quarter', 'UW tuition',
 'Prerequisite: CSS 422 or equivalent.',
 'Verify prerequisite chain on MyPlan.'),

('CSS 432 – Network Programming',
 'course',
 'bothell',
 'TCP/IP networking, socket programming, client-server architecture, and network protocol implementation. Provides hands-on experience building networked applications in C/C++. Relevant for backend, distributed systems, and cloud infrastructure roles.',
 ARRAY['networking','socket programming','c','c++','tcp/ip','distributed systems','protocol design'],
 'https://myplan.uw.edu/course/#/courses/CSS%20432',
 TRUE, '2026-05-12', 'pending',
 '10 weeks, ~15 hours/week', 'one quarter', 'UW tuition',
 'Prerequisite: CSS 430.',
 'Verify prerequisite on MyPlan.'),

('CSS 436 – Cloud Computing',
 'course',
 'bothell',
 'Hands-on cloud computing course covering AWS or equivalent, distributed systems concepts, serverless computing, containers, and scalable application design. Direct preparation for cloud engineering, DevOps, and backend SWE roles.',
 ARRAY['cloud computing','aws','docker','distributed systems','devops','serverless','kubernetes','scalability'],
 'https://myplan.uw.edu/course/#/courses/CSS%20436',
 TRUE, '2026-05-12', 'pending',
 '10 weeks, ~15 hours/week', 'one quarter', 'UW tuition',
 'Check prerequisites on MyPlan.',
 'Verify offering schedule and whether AWS credits are provided.'),

('CSS 440 – Software Engineering Project',
 'course',
 'bothell',
 'Capstone software engineering course involving team-based development of a full-stack application from requirements gathering through delivery. Covers Agile practices, CI/CD, code review, and professional engineering workflows. Strong resume signal demonstrating end-to-end project ownership.',
 ARRAY['software engineering','agile','teamwork','full-stack development','project management','git','ci/cd','requirements engineering'],
 'https://myplan.uw.edu/course/#/courses/CSS%20440',
 TRUE, '2026-05-12', 'pending',
 '10 weeks, ~20 hours/week', 'one quarter', 'UW tuition',
 'Prerequisite: CSS 480.',
 'Verify prerequisite on MyPlan. Projects are typically showcased at the end-of-year event.'),

('CSS 452 – Programming Languages',
 'course',
 'bothell',
 'Survey of programming language design including syntax, semantics, type systems, functional programming, and language implementation. Broadens language fluency relevant to compiler, interpreter, and language tooling roles.',
 ARRAY['programming languages','functional programming','type systems','compilers','language design','haskell'],
 'https://myplan.uw.edu/course/#/courses/CSS%20452',
 TRUE, '2026-05-12', 'pending',
 '10 weeks, ~12 hours/week', 'one quarter', 'UW tuition',
 'Check prerequisites on MyPlan.',
 'Verify offering schedule; may be offered once per year.'),

('CSS 471 – Introduction to Artificial Intelligence',
 'course',
 'bothell',
 'Introductory AI course covering search algorithms, constraint satisfaction, probabilistic reasoning, and machine learning fundamentals. Provides conceptual grounding for AI engineering, data science, and ML-adjacent software roles.',
 ARRAY['artificial intelligence','python','machine learning','search algorithms','probabilistic reasoning','constraint satisfaction'],
 'https://myplan.uw.edu/course/#/courses/CSS%20471',
 TRUE, '2026-05-12', 'pending',
 '10 weeks, ~12 hours/week', 'one quarter', 'UW tuition',
 'Check prerequisites on MyPlan.',
 'Verify offering schedule.'),

('CSS 475 – Computer Networking',
 'course',
 'bothell',
 'In-depth study of computer network protocols, the OSI model, TCP/IP stack, routing algorithms, and network security fundamentals. Relevant for network engineering, cloud infrastructure, and backend systems roles.',
 ARRAY['networking','tcp/ip','network protocols','security','routing','wireshark'],
 'https://myplan.uw.edu/course/#/courses/CSS%20475',
 TRUE, '2026-05-12', 'pending',
 '10 weeks, ~12 hours/week', 'one quarter', 'UW tuition',
 'Check prerequisites on MyPlan.',
 'Verify offering schedule and confirm it is distinct from CSS 432.'),

('CSS 480 – Introduction to Software Engineering',
 'course',
 'bothell',
 'Covers the software development lifecycle, requirements engineering, design patterns, testing methodologies, and team development practices. Foundation course for the CSS capstone and directly applicable to industry software engineering roles.',
 ARRAY['software engineering','design patterns','testing','agile','requirements engineering','object-oriented design'],
 'https://myplan.uw.edu/course/#/courses/CSS%20480',
 TRUE, '2026-05-12', 'pending',
 '10 weeks, ~12 hours/week', 'one quarter', 'UW tuition',
 'Prerequisite: CSS 343. Verify on MyPlan.',
 'Typically required before CSS 440 (capstone).'),

('CSS 484 – Database Management Systems',
 'course',
 'bothell',
 'Relational database design, SQL, normalization, transactions, indexing, and query optimization. Essential for backend software engineering, data engineering, and full-stack development roles.',
 ARRAY['sql','databases','data modeling','postgresql','query optimization','transactions','relational algebra'],
 'https://myplan.uw.edu/course/#/courses/CSS%20484',
 TRUE, '2026-05-12', 'pending',
 '10 weeks, ~12 hours/week', 'one quarter', 'UW tuition',
 'Check prerequisites on MyPlan.',
 'Verify offering schedule.'),

('CSS 487 – Machine Learning',
 'course',
 'bothell',
 'Practical machine learning course covering supervised learning, unsupervised learning, neural networks, model evaluation, and ML engineering practices using Python. Strong resume credential for ML engineering, data science, and AI product roles.',
 ARRAY['machine learning','python','scikit-learn','neural networks','deep learning','data science','pytorch','model evaluation'],
 'https://myplan.uw.edu/course/#/courses/CSS%20487',
 TRUE, '2026-05-12', 'pending',
 '10 weeks, ~15 hours/week', 'one quarter', 'UW tuition',
 'Check prerequisites (CSS 343 and linear algebra recommended). Verify on MyPlan.',
 'Verify offering schedule.'),

('CSS 490 – Special Topics in Computing',
 'course',
 'bothell',
 'Variable-topic advanced course. Past topics include web development, open-source software engineering, applied AI, and security. Skills earned vary by topic. Check the current quarter''s MyPlan listing for the active topic.',
 ARRAY['varies by topic','software development','specialized computing'],
 'https://myplan.uw.edu/course/#/courses/CSS%20490',
 TRUE, '2026-05-12', 'pending',
 '10 weeks, ~10–15 hours/week', 'one quarter', 'UW tuition',
 'Check current quarter''s SDB/MyPlan for available sections and topics.',
 'Topic changes each quarter. Must re-verify skills and description each time a new section is added.'),

-- ── RESEARCH ─────────────────────────────────────────────────────────────────

('CSS 499 – Directed Research',
 'research',
 'bothell',
 'Independent research course supervised by a CSS faculty member. Students propose and complete a research project in a computing subdomain. Produces a faculty reference and a research artifact — two of the strongest differentiators in competitive internship and graduate school applications.',
 ARRAY['research','independent study','technical writing','problem solving','project management','academic presentation'],
 'https://www.uwb.edu/css/research',
 TRUE, '2026-05-12', 'pending',
 '10 weeks, ~10 hours/week', 'one quarter (repeatable)', 'UW tuition (1–5 credits)',
 'Contact a CSS faculty member directly to propose a project before registering.',
 'Requires faculty sponsorship. Confirm current faculty research areas on the CSS department website.'),

('UW Undergraduate Research Program (URP)',
 'research',
 'bothell',
 'UW-wide program connecting undergraduates with paid or for-credit research positions across all departments. CSS students can apply for computing and data science research roles with UW Seattle and UWB faculty.',
 ARRAY['research','academic writing','data analysis','problem solving','python','statistics'],
 'https://www.washington.edu/undergradresearch/',
 TRUE, '2026-05-12', 'pending',
 '10–15 hours/week during active quarters', 'one quarter or longer, renewable', 'paid stipend or academic credit',
 'Applications accepted on a rolling basis; check URP site for current open positions.',
 'Verify the URP site is current and that UW students are explicitly eligible.'),

('UWB STARS – Summer Teaching and Research Scholars',
 'research',
 'bothell',
 'Competitive summer program at UW Bothell pairing undergraduates with faculty mentors for an intensive research project. Participants present findings at the end-of-summer symposium. Strong credential for graduate school applications and research-oriented industry roles.',
 ARRAY['research','academic presentation','project management','technical writing','mentorship'],
 'https://www.uwb.edu/stars',
 TRUE, '2026-05-12', 'pending',
 'full-time summer, ~40 hours/week for 8–10 weeks', 'one summer', 'paid stipend provided',
 'Competitive application; deadlines typically in late winter quarter. Check uwb.edu/stars for dates.',
 'Verify program is active for the upcoming summer and confirm application deadline.'),

('UW Reality Lab (XRML)',
 'research',
 'bothell',
 'UW research lab focused on extended reality (XR), augmented reality (AR), and virtual reality (VR). Open to students from the UW system including UWB. Demonstrates applied graphics, HCI, and systems programming skills in a high-visibility research lab.',
 ARRAY['augmented reality','virtual reality','computer graphics','unity','c++','human-computer interaction','research'],
 'https://realitylab.uw.edu',
 TRUE, '2026-05-12', 'pending',
 '10–20 hours/week depending on project', 'ongoing while enrolled', 'unpaid or paid depending on funding',
 'Contact Reality Lab faculty or graduate students directly.',
 'Verify lab is actively recruiting undergraduates and confirm contact process.'),

('CSS Faculty Research Labs at UWB',
 'research',
 'bothell',
 'Individual CSS faculty at UWB maintain active research in areas including security, machine learning, HCI, databases, and software engineering. Students can join a lab via CSS 499 or by emailing faculty directly. Lab membership is among the strongest resume signals for research and advanced engineering roles.',
 ARRAY['research','machine learning','cybersecurity','databases','human-computer interaction','software engineering'],
 'https://www.uwb.edu/css/faculty',
 TRUE, '2026-05-12', 'pending',
 '10–15 hours/week', 'one or more quarters', 'academic credit or paid (depends on faculty funding)',
 'Email faculty directly with a brief research interest statement and transcript.',
 'Verify current faculty research areas and which faculty are actively accepting undergraduates.'),

('NSF Research Experiences for Undergraduates (REU)',
 'research',
 'bothell',
 'National Science Foundation-funded summer research programs at universities nationwide. UW students are eligible to apply. REU participation is one of the strongest research credentials for computing undergraduates applying to graduate programs or research-adjacent industry roles.',
 ARRAY['research','machine learning','algorithms','systems programming','academic writing','public speaking'],
 'https://www.nsf.gov/crssprgm/reu/list.jsp',
 TRUE, '2026-05-12', 'pending',
 'full-time summer, 10 weeks', 'one summer', 'paid stipend plus housing allowance',
 'Applications open in winter quarter; deadlines vary by site. Search NSF REU list for computing-focused sites.',
 'Programs are site-specific; students apply to individual sites nationwide.'),

('UWB Discovery Core – Research and Creative Practice Component',
 'research',
 'bothell',
 'The Discovery Core curriculum at UWB includes a required research or community-engaged learning component. CSS students may satisfy this with faculty-supervised computing research projects, linking general education requirements to tangible resume content.',
 ARRAY['research','interdisciplinary thinking','inquiry','academic writing'],
 'https://www.uwb.edu/discoverycore',
 TRUE, '2026-05-12', 'pending',
 'one quarter, ~5–10 hours/week', 'one quarter', 'UW tuition',
 'Typically fulfilled through designated Discovery Core-tagged courses. Confirm options with an academic advisor.',
 'Verify the Discovery Core research track is still part of current UWB general education requirements.'),

-- ── FELLOWSHIPS ──────────────────────────────────────────────────────────────

('UW Lavin Entrepreneurship Program',
 'fellowship',
 'bothell',
 'Competitive entrepreneurship program providing mentorship, workshops, and seed funding support for student startup founders. Relevant for CSS students targeting product management, startup founding, or tech entrepreneurship roles.',
 ARRAY['entrepreneurship','product development','leadership','business development','pitching','startup'],
 'https://foster.uw.edu/centers/lavin-entrepreneurship-center/',
 TRUE, '2026-05-12', 'pending',
 'varies; workshops plus independent project work', 'one or more quarters', 'free',
 'Competitive application; check Foster School website for dates and eligibility.',
 'Verify whether UW students (not just UW Seattle) are eligible to apply.'),

('Management Leadership for Tomorrow (MLT) Early Careers',
 'fellowship',
 'bothell',
 'Selective national fellowship supporting underrepresented students of color pursuing careers in business, technology, and social sectors. Fellows gain access to corporate recruiting pipelines, executive coaching, and a professional network spanning major tech companies.',
 ARRAY['leadership','professional development','networking','business acumen','career planning'],
 'https://mlt.org/early-career-programs/',
 TRUE, '2026-05-12', 'pending',
 'ongoing program over 1–2 years', 'multi-year fellowship', 'free (selective admission)',
 'Applications typically open in summer for fall start. Check mlt.org for current cycle.',
 'Verify eligibility criteria and application window.'),

('Rewriting the Code (RTC) Fellowship',
 'fellowship',
 'bothell',
 'National fellowship supporting women and gender-diverse students in computing. Benefits include mentorship, networking with tech companies, access to exclusive recruiting events, and a community of 25,000+ peers. Open to UW students.',
 ARRAY['professional development','networking','leadership','software engineering','community building'],
 'https://rewritingthecode.org',
 TRUE, '2026-05-12', 'pending',
 'self-directed; attend virtual events as available', 'ongoing membership while enrolled', 'free',
 'Apply at rewritingthecode.org. Applications reviewed on a rolling basis.',
 'Verify current eligibility requirements and application process.'),

('Microsoft Explore Program',
 'fellowship',
 'bothell',
 'Microsoft''s early-stage internship for first- and second-year students from underrepresented groups. Participants rotate through software engineering, program management, and UX research over 12 weeks in Redmond — directly accessible for UW students by geography.',
 ARRAY['software development','product management','ux research','professional development','microsoft technologies'],
 'https://careers.microsoft.com/students/us/en/usexploremicrosoftprogram',
 TRUE, '2026-05-12', 'pending',
 '12 weeks, full-time summer', 'one summer', 'paid internship',
 'Applications open in September–November for the following summer. Apply at Microsoft Careers.',
 'Verify current application window. Must be freshman or sophomore at time of application.'),

('Amazon Future Engineer Scholarship and Internship',
 'fellowship',
 'bothell',
 'Scholarship and internship program from Amazon for students from underrepresented communities pursuing CS degrees. Recipients receive scholarship funds and a guaranteed internship offer. Both the scholarship and the internship are resume-ready credentials.',
 ARRAY['software engineering','cloud computing','aws','professional development'],
 'https://www.amazonfutureengineer.com/scholarships',
 TRUE, '2026-05-12', 'pending',
 'internship is 12 weeks summer; scholarship has no time commitment', 'one summer internship; scholarship is annual renewable', 'free',
 'Applications typically open in fall quarter. Check amazonfutureengineer.com for current cycle.',
 'Verify current eligibility criteria (GPA, financial need, year in school).'),

-- ── PROGRAMS ─────────────────────────────────────────────────────────────────

('CodePath University Programs',
 'program',
 'bothell',
 'Free technical courses offered by CodePath in partnership with universities including UWB. Courses cover web development, mobile development, cybersecurity, and technical interview preparation. Designed to close the gap between standard coursework and industry-ready engineering skills.',
 ARRAY['web development','mobile development','cybersecurity','technical interviews','python','javascript','swift'],
 'https://www.codepath.org',
 TRUE, '2026-05-12', 'pending',
 '~5 hours/week for 8–12 weeks', 'one semester per course; multiple courses available', 'free',
 'Apply at codepath.org. Courses fill quickly; apply at the start of each semester.',
 'Verify UWB is an active CodePath partner school and which courses are available this semester.'),

('UW Career Center – Husky Career Advantage',
 'program',
 'bothell',
 'Structured professional development program from the UW Career Center available to all UW students including UWB. Participants complete milestones in resume building, networking, interview preparation, and career planning to earn a credential.',
 ARRAY['professional development','resume writing','networking','interview preparation','career planning'],
 'https://careers.uw.edu',
 TRUE, '2026-05-12', 'pending',
 'self-paced; estimated 5–10 hours total', 'self-paced, complete any time while enrolled', 'free with UW NetID',
 'Log in with your UW NetID at careers.uw.edu.',
 'Verify whether the Husky Career Advantage credential is still actively offered and that UW students can access the UW Career Center.'),

('UWB Undergraduate Mentorship Program',
 'program',
 'bothell',
 'UWB program pairing undergraduates with alumni or industry mentors in their field. Regular one-on-one meetings support career exploration, job search strategy, and professional skill development.',
 ARRAY['professional development','networking','mentorship','career planning','communication'],
 'https://www.uwb.edu/careers',
 TRUE, '2026-05-12', 'pending',
 '1–2 hours/month', 'one quarter or full academic year', 'free',
 'Sign up through the UWB Career Services office.',
 'Verify program is currently active and accepting new mentee applications.'),

('UWB Global Studies – Study Abroad and International Programs',
 'program',
 'bothell',
 'UWB programs allowing students to pursue international academic or research experiences. International experience differentiates candidates in tech roles targeting global teams, international markets, or cross-cultural product development.',
 ARRAY['cultural competency','adaptability','global perspective','communication','independence'],
 'https://www.uwb.edu/global',
 TRUE, '2026-05-12', 'pending',
 'one quarter or full academic year abroad', 'one quarter minimum', 'varies; financial aid may apply',
 'Contact the UWB Global Studies office one full quarter before intended travel.',
 'Verify current program offerings and confirm financial aid portability for UW students.'),

-- ── EVENTS ───────────────────────────────────────────────────────────────────

('UWB Hackathon',
 'event',
 'bothell',
 'Annual hackathon hosted at UW Bothell where students form teams and build projects over 24–48 hours. Participation demonstrates initiative, rapid prototyping ability, and teamwork. The resulting project can be showcased in a portfolio and discussed in interviews.',
 ARRAY['software development','teamwork','rapid prototyping','problem solving','full-stack development'],
 'https://www.uwb.edu/css/events',
 TRUE, '2026-05-12', 'pending',
 '24–48 hours, one weekend', 'one weekend event', 'free',
 'Registration opens a few weeks before the event. Check uwb.edu/css/events for current dates.',
 'Verify the UWB Hackathon is scheduled for the current academic year and confirm the date.'),

('DiamondHacks (UW Seattle Hackathon)',
 'event',
 'bothell',
 'Major League Hacking-affiliated hackathon at UW Seattle open to all UW students, including UWB. Larger competition with sponsor prizes and networking opportunities with tech company recruiters.',
 ARRAY['software development','teamwork','rapid prototyping','networking','problem solving'],
 'https://mlh.io/seasons/2026/events',
 TRUE, '2026-05-12', 'pending',
 '24–36 hours, one weekend', 'one weekend event', 'free',
 'Register via MLH or the DiamondHacks website.',
 'Verify DiamondHacks is scheduled for the current year and confirm UW student eligibility.'),

('UWB Career and Internship Fair',
 'event',
 'bothell',
 'Biannual career fair at UW Bothell connecting students with local and national employers. Attending with a targeted resume and pre-researched company list can yield direct recruiter contacts and interview pipeline access. Held each autumn and spring quarter.',
 ARRAY['networking','professional communication','resume presentation','career planning'],
 'https://www.uwb.edu/careers/career-fair',
 TRUE, '2026-05-12', 'pending',
 'half-day event', 'one day, twice per year', 'free with UW student ID',
 'Register through Handshake or uwb.edu/careers. Walk-ins also typically accepted.',
 'Verify current semester date and whether pre-registration is required.'),

('CSS Student Showcase',
 'event',
 'bothell',
 'End-of-year event where CSS students present capstone and research projects to faculty, industry guests, and peers. Presenting at the showcase demonstrates completed project work, technical communication, and public presentation skills.',
 ARRAY['public speaking','software development','project completion','technical communication','demo skills'],
 'https://www.uwb.edu/css/events',
 TRUE, '2026-05-12', 'pending',
 'one afternoon (event day) plus preparation', 'annual event', 'free',
 'Enrollment in CSS 440 typically provides automatic entry. Check with CSS department for standalone submission options.',
 'Verify event is held in the current academic year and confirm submission process.'),

('Major League Hacking (MLH) Member Events',
 'event',
 'bothell',
 'Series of student hackathons affiliated with Major League Hacking, held throughout the year at universities in the Pacific Northwest and online. UW students regularly participate. Hackathon projects strengthen portfolios, GitHub activity, and professional profiles.',
 ARRAY['software development','teamwork','problem solving','rapid prototyping','portfolio building'],
 'https://mlh.io',
 TRUE, '2026-05-12', 'pending',
 '24–36 hours per event', 'recurring throughout the year', 'free or low registration fee',
 'Browse and register at mlh.io for upcoming events.',
 'Verify current MLH event schedule includes PNW or online events accessible to UW students.'),

('Grace Hopper Celebration (GHC) – Student Scholar Track',
 'event',
 'bothell',
 'World''s largest gathering of women technologists. Student scholar applications are available for UW students, especially those in WiC. Attendance connects students with major tech company recruiters and role models. In-person and virtual tracks available.',
 ARRAY['networking','professional development','diversity and inclusion','career exploration'],
 'https://ghc.anitab.org',
 TRUE, '2026-05-12', 'pending',
 '3–5 days (conference week)', 'annual conference', 'student scholar scholarship covers registration; travel funding varies',
 'Apply for student scholarship at ghc.anitab.org. Applications typically open in spring for fall conference.',
 'Verify current year scholarship deadline and whether virtual attendance is still offered.'),

('UWB Research Day Symposium',
 'event',
 'bothell',
 'Annual UW Bothell event where students present research projects to faculty, industry guests, and peers. Presenting at Research Day demonstrates public speaking, research communication, and completed independent project experience.',
 ARRAY['research','public speaking','academic presentation','technical communication','poster design'],
 'https://www.uwb.edu/research/undergraduate-research',
 TRUE, '2026-05-12', 'pending',
 'one day (presentation day) plus preparation time', 'annual event', 'free',
 'Submit abstract through the UWB Research office. Deadlines are typically mid-winter quarter.',
 'Verify current academic year dates and abstract submission deadline.'),

('Seattle Tech Meetups and Open Houses',
 'event',
 'bothell',
 'Regular industry meetups hosted by Seattle-area tech companies and professional groups. Attending demonstrates professional initiative and provides networking contacts outside the campus environment. Searchable on Meetup.com and Eventbrite.',
 ARRAY['networking','professional development','industry awareness','communication'],
 'https://www.meetup.com/cities/us/wa/seattle/tech/',
 TRUE, '2026-05-12', 'pending',
 '1–3 hours per event', 'recurring; multiple events per month', 'typically free',
 'Search and RSVP on Meetup.com or Eventbrite using ''Seattle tech'' as the search term.',
 'No single event to verify; confirm at least one active Seattle tech meetup group is currently running.');
